# Interactive graph

<style>
  * {
    font-family: sans-serif;
  }
    #container {
      display: flex;
      justify-content: space-between;
    }

    #plot-container {
      flex: 2;
      margin-right: 20px;
      display: flex;
      flex-direction: column;
    }

    #plot {
      margin-bottom: 20px;
    }

    #legends {
      display: flex;
      flex-wrap: wrap;
      font-size: 12px;
    }

    #barplot {
      flex: 1;
      margin-left: 20px;
    }
    
    .button-container {
    margin-bottom: 20px;
    margin-left: 350px;
  }

  .button-container h3 {
    margin: 5px 0;
    font-size: 16px;
    font-weight: bold;
  }

  .gender-buttons button, .country-buttons button {
    background-color: #007BFF;
    color: white;
    border: none;
    border-radius: 5px;
    padding: 10px 15px;
    margin: 5px;
    cursor: pointer;
    transition: background-color 0.3s ease;
  }

  .gender-buttons button:hover, .country-buttons button:hover {
    background-color: #0056b3;
  }

  .gender-buttons button.active, .country-buttons button.active {
    background-color: #28a745;
  }

    .legend-item {
      margin-right: 10px;
      display: flex;
      align-items: center;
    }

    .legend-color {
      width: 10px;
      height: 10px;
      margin-right: 5px;
    }

    .tooltip {
      position: absolute;
      visibility: hidden;
      background: rgba(0, 0, 0, 0.8);
      color: white;
      padding: 5px;
      border-radius: 5px;
      font-size: 12px;
    }
</style> 

<body>

<div id="container"><div id="plot"></div><div id="barplot"></div></div>

<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
<script src="scripts/myscript.js"></script>

</body>